export const publicStrategies = [
  {slug:"large-cap",name:"Large Cap Club",type:"Equity",theme:"Foundation",universe:"Large-cap equities",title:"Established businesses. A systematic perspective.",description:"A disciplined framework for exploring India’s large-cap equity universe through defined selection and portfolio construction rules.",lens:"Explore established companies through a consistent research lens, with a clearly described universe and portfolio approach.",shape:"large"},
  {slug:"mid-cap",name:"Mid Cap Club",type:"Equity",theme:"Evolution",universe:"Mid-cap equities",title:"An evolving universe. A consistent process.",description:"A structured approach to the mid-cap universe, applying repeatable research principles to selection and construction.",lens:"Understand how an evolving investment universe can be approached through documented eligibility and selection principles.",shape:"mid"},
  {slug:"small-cap",name:"Small Cap Club",type:"Equity",theme:"Discovery",universe:"Small-cap equities",title:"Look deeper. Stay disciplined.",description:"A systematic lens on small-cap equities, built around a defined investment universe and a repeatable selection process.",lens:"Explore the role of a defined research framework when considering smaller companies, with attention to the scope and limits of the model.",shape:"small"},
  {slug:"multi-cap",name:"Multi Cap Club",type:"Equity",theme:"Perspective",universe:"Equities across market caps",title:"A broader universe. One research philosophy.",description:"A quantitative framework that explores equities across market-cap segments through a consistent construction process.",lens:"Bring different market-cap segments into a common research framework while keeping the strategy’s mandate clear.",shape:"multi"},
  {slug:"diversified-funds",name:"Diversified Mutual Fund Club",type:"Mutual funds",theme:"Structure",universe:"Diversified mutual funds",title:"Many possibilities. A considered structure.",description:"A systematic approach to diversified mutual-fund selection, bringing a documented framework to model portfolio construction.",lens:"Start with the purpose of the portfolio, then explore how the fund universe and selection framework support that purpose.",shape:"funds"},
  {slug:"sector-rotation",name:"Sector Rotation Club",type:"Mutual funds",theme:"Adaptation",universe:"Sector & thematic mutual funds",title:"Markets evolve. The process endures.",description:"A rules-based research framework for sector and thematic fund allocation, with a clearly defined review process.",lens:"Explore the thinking behind sector allocation, the investment universe and the role of a scheduled review process.",shape:"sector"},
];

export const processSteps = [
  {title:"Define",subtitle:"A clear investment universe",body:"Start with a defined universe and documented eligibility principles. Establish what belongs in the research before considering portfolio construction."},
  {title:"Evaluate",subtitle:"A consistent research lens",body:"Apply quantitative signals and selection rules within a repeatable framework. Make the purpose of the methodology understandable."},
  {title:"Construct",subtitle:"A disciplined portfolio structure",body:"Translate the research into an equally weighted model portfolio at its scheduled rebalance, following the strategy’s construction rules."},
  {title:"Publish",subtitle:"A dated, shared research record",body:"Organise portfolio releases and supporting documents so your team can follow the research and each portfolio’s review schedule."},
];

export type Article = {slug:string;category:string;title:string;dek:string;art:string;status:"draft"|"published";author?:string;publishedAt?:string;sections:{title:string;paragraphs:string[]}[]};

// Editorial concepts written for the design preview. These are not claimed as published company articles.
export const articles:Article[] = [
  {slug:"the-process-behind-the-portfolio",category:"Research process",title:"The process behind the portfolio.",dek:"Why the questions behind a strategy matter as much as the portfolio it produces.",art:"orbits",status:"draft",sections:[
    {title:"Begin with the question",paragraphs:["A portfolio is the visible outcome of a research process. Before considering that outcome, it helps to understand the question the strategy is designed to address: which universe does it examine, what is it trying to organise, and what sits outside its scope?","Our approach begins with these definitions. They provide a common language for discussing the research with an advisory team."]},
    {title:"Make the framework understandable",paragraphs:["A methodology introduction should explain the role of selection, construction and review. It need not expose proprietary parameters to give a useful account of how those stages fit together.","For an adviser, this context supports a more informed conversation about the intended use of the research. A clearly described process also makes its limitations easier to discuss."]},
    {title:"Keep the record connected",paragraphs:["The methodology, portfolio publication and supporting notes should be easy to find together. A dated document tells the reader which version they are looking at and where it belongs in the research record.","That is the experience we are designing at The Quant Club: a place where the portfolio remains connected to the thinking behind it."]},
  ]},
  {slug:"equal-weighting-is-a-design-choice",category:"Portfolio construction",title:"Equal weighting is a design choice.",dek:"A closer look at the role of a clear allocation rule in a systematic portfolio.",art:"grid",status:"draft",sections:[
    {title:"Define the allocation rule",paragraphs:["A portfolio framework includes both what is selected and how the selected holdings are represented. Equal weighting describes an allocation rule applied at the portfolio’s scheduled construction or rebalance point.","The Quant Club uses equal weighting in its model portfolios. The purpose of explaining that rule is to make the construction process visible to the adviser."]},
    {title:"Separate construction from selection",paragraphs:["The decision about which holdings belong in a portfolio is distinct from the decision about their starting weights. Describing the two stages separately gives a clearer account of the methodology.","An allocation rule does not replace the need to understand the strategy’s universe, its review process or its limitations."]},
    {title:"Keep the context with the portfolio",paragraphs:["A dated portfolio should identify the construction convention used. Readers should be able to distinguish a model’s target allocations from any separately observed holdings.","Our public introductions explain the framework. Portfolio-specific information belongs within the appropriate member access level."]},
  ]},
  {slug:"publication-is-not-rebalancing",category:"Portfolio construction",title:"A publication date is not a rebalance date.",dek:"Understanding the distinction between a fresh research release and a portfolio’s own review cycle.",art:"paths",status:"draft",sections:[
    {title:"Different dates have different jobs",paragraphs:["A publication date identifies when a research release becomes available. A rebalance date belongs to the review schedule of a particular portfolio. Treating them as interchangeable can make a portfolio record difficult to follow.","Our product design keeps those concepts separate, so each release can be read in the context of the portfolio it describes."]},
    {title:"Allow for different starting points",paragraphs:["Advisory firms may begin using a research portfolio at different times. Monthly publications support those different entry points while each portfolio follows its own scheduled review cycle.","A new monthly release does not by itself mean that every existing portfolio is being rebalanced."]},
    {title:"Build a readable record",paragraphs:["Clear labels help: publication date, applicable portfolio and review schedule each answer a different question. Supporting documents should use the same terminology.","The aim is an organised research history that advisers can interpret without having to reconstruct the sequence from disconnected files."]},
  ]},
  {slug:"a-shared-research-language",category:"Adviser practice",title:"Give your team a shared research language.",dek:"How consistent terminology and organised documents support a clearer advisory workflow.",art:"network",status:"draft",sections:[
    {title:"Start with shared definitions",paragraphs:["A strategy name is a starting point, not a complete description. Teams also need a shared understanding of the investment universe, the portfolio approach and the purpose of each publication.","Consistent language helps colleagues discuss the same research without relying on assumptions about what a term means."]},
    {title:"Keep context easy to find",paragraphs:["A methodology note, a portfolio release and a general educational article serve different purposes. Organising those materials by role helps readers find the context they need.","A shared workspace should make those distinctions visible while keeping the related material connected."]},
    {title:"Preserve the adviser’s role",paragraphs:["Research is an input to an advisory practice. Client relationships, suitability decisions and execution remain with the firm.","The Quant Club is being built around that division of responsibilities: focused research tools for professionals who retain their own advisory judgement."]},
  ]},
  {slug:"reading-a-strategy-methodology",category:"Research process",title:"What to look for in a methodology note.",dek:"The universe, the construction rule, the review process—and the questions worth asking.",art:"layers",status:"draft",sections:[
    {title:"Understand the scope",paragraphs:["Begin with the strategy’s stated universe and purpose. A useful introduction tells you what the framework considers and where its boundaries lie.","This context makes subsequent discussion of selection and portfolio construction more precise."]},
    {title:"Connect the stages",paragraphs:["Look for an explanation of how eligibility, selection, construction and review relate to one another. These stages should read as parts of a coherent process.","Where a description leaves a question open, a research walkthrough is an opportunity to ask for clarification rather than fill the gap with an assumption."]},
    {title:"Ask about documentation",paragraphs:["The research record should distinguish general methodology from portfolio-specific information. It should also make the relevant version or publication context understandable.","We want those conversations to be accessible: begin with the framework, understand its limits, then explore the information available through the appropriate access level."]},
  ]},
  {slug:"research-and-technology",category:"Adviser practice",title:"Where research meets a better workflow.",dek:"The thinking behind a platform that connects investment ideas with the way advisory teams work.",art:"signal",status:"draft",sections:[
    {title:"Begin with the research task",paragraphs:["Technology has a useful role when it makes the research process easier to understand and follow. For an advisory team, that can begin with a simple task: finding the current document and knowing what it describes.","Our platform design starts with those practical research needs rather than adding features without a defined purpose."]},
    {title:"Design for the whole team",paragraphs:["A shared view of strategy information and publication updates gives colleagues a common starting point. Clear navigation and meaningful labels help preserve the context as they move between documents.","The interface should support the research, with each screen explaining what is being shown and how it relates to the strategy."]},
    {title:"Keep the boundaries clear",paragraphs:["Public education, member research and the firm’s own client decisions serve different roles. The product should make those boundaries understandable.","That is our direction for The Quant Club: quantitative research, delivered through a platform designed around the advisory practice."]},
  ]},
];

export const commonQuestions = [
  ["Who is The Quant Club built for?","Registered investment advisers and their teams looking for a systematic research framework to support their advisory practice."],
  ["Where can I see strategy figures?","The public website does not show strategy figures, holdings or performance charts. Approved members will see only the permitted live data and information after signing in."],
  ["What happens in a strategy walkthrough?","We discuss your firm’s research needs, introduce the strategy universes and explain the portfolio process and workspace."],
  ["Does monthly publication mean monthly rebalancing?","No. A new portfolio is published each month for different entry dates. Each portfolio follows its own scheduled rebalance cycle."],
  ["Do you manage clients or execute trades?","The platform provides research and model portfolios. Client management, suitability decisions and execution remain with the advisory firm."],
];
