"use client";

import Link from "next/link";
import { QuantLogo } from "./logo";
import { PlatformCycle } from "./platform-cycle";
import { useState } from "react";
import { ArrowRight, ArrowLeftRight, BarChart3, Building2, Check, ChevronRight, CircleHelp, Droplets, FileChartColumn, FileText, Landmark, Layers3, LayoutDashboard, ListChecks, LockKeyhole, PieChart, Search, Settings, ShieldCheck, TrendingUp, Users, Workflow, type LucideIcon } from "lucide-react";
import { publicStrategies } from "@/lib/public-content";

export function ReferenceLogo(){return <span className="r-logo"><QuantLogo compact/><span>The Quant Club</span></span>;}

function Waves({id="waves"}:{id?:string}){return <svg className="r-waves" viewBox="0 0 1440 580" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id={`${id}-a`} x1="0" y1="1" x2="1" y2="0"><stop stopColor="#d2f1ff" stopOpacity=".16"/><stop offset="1" stopColor="#80c4ff" stopOpacity=".52"/></linearGradient><linearGradient id={`${id}-b`} x1="0" y1="1" x2="1" y2="0"><stop stopColor="#b9e3ff" stopOpacity=".1"/><stop offset="1" stopColor="#abd6ff" stopOpacity=".62"/></linearGradient></defs><path d="M-60 310C160 210 170 630 420 470S710 465 920 180 1180 90 1480-90V240C1190 290 1150 180 950 350S675 465 420 515 160 470-60 410Z" fill={`url(#${id}-a)`}/><path d="M-70 315C155 280 180 510 400 480S710 190 935 120 1230-30 1490-100V50C1250 150 1130 210 940 230S660 530 430 525 100 425-70 465Z" fill={`url(#${id}-b)`}/><path d="M-40 430C250 575 340 570 560 450S815 470 1110 285 1340 250 1490 170V300C1310 270 1200 440 1020 417S690 510 550 511 200 591-40 478Z" fill={`url(#${id}-b)`}/>{Array.from({length:12},(_,i)=><path key={i} d={`M-40 ${337+i*6}C155 ${255+i*6} 185 ${515+i*3} 410 ${489+i*2}S820 ${130+i*5} 1050 ${145+i*4} 1300 ${38+i*7} 1480 ${-10+i*7}`} fill="none" stroke="#9bd3fb" strokeWidth=".6" opacity=".2"/>)}</svg>;}

const dashboardCards:{title:string;copy:string;icon:LucideIcon;color:string}[]=[
 {title:"Strategy Research",copy:"Explore our research and strategies",icon:BarChart3,color:"blue"},
 {title:"Model Portfolios",copy:"View portfolio structure and methodology",icon:PieChart,color:"teal"},
 {title:"Rebalance Center",copy:"Follow the portfolio review process",icon:ArrowLeftRight,color:"blue"},
 {title:"Reports & Analytics",copy:"Research context for your team",icon:FileChartColumn,color:"blue"},
 {title:"Client Deployment",copy:"An adviser-led implementation workflow",icon:Users,color:"blue"},
];

export function DashboardPreview({expanded=false}:{expanded?:boolean}){
 const [active,setActive]=useState("Dashboard");
 const navigation=[{label:"Dashboard",icon:LayoutDashboard},{label:"Research",icon:FileText},{label:"Model Portfolios",icon:Layers3},{label:"Rebalance & Orders",icon:ListChecks},{label:"Clients",icon:Users},{label:"Reports",icon:FileChartColumn},{label:"Settings",icon:Settings}];
 return <div className={`r-dashboard ${expanded?"r-dashboard-expanded":""}`}><div className="r-dashboard-top"><ReferenceLogo/><div className="r-dashboard-search"><Search size={10}/><span>Research, strategies, workflows</span></div><span className="r-preview-tag">PLATFORM CONCEPT</span><span className="r-avatar">A</span></div><div className="r-dashboard-body"><nav aria-label="Dashboard concept navigation">{navigation.map(({label,icon:Icon})=><button key={label} aria-pressed={active===label} onClick={()=>setActive(label)}><Icon size={12}/><span>{label}</span></button>)}</nav><div className="r-dashboard-main"><div className="r-dashboard-heading"><div><h3>{active==="Dashboard"?"Good morning":active}</h3><p>{active==="Dashboard"?"Turn research into a more disciplined investment process.":"Explore the connected investment workflow."}</p></div><LockKeyhole size={12}/></div>{active==="Dashboard"?<><div className="r-dashboard-cards">{dashboardCards.map(({title,copy,icon:Icon,color})=><Link key={title} href="/platform" className={`r-dashboard-card ${color}`}><span><Icon size={21}/></span><h4>{title}</h4><p>{copy}</p></Link>)}</div><div className="r-dashboard-lower"><div><h4>Research to implementation</h4><div className="r-mini-flow"><span><Search size={15}/>Research</span><ChevronRight size={12}/><span><Layers3 size={15}/>Portfolio</span><ChevronRight size={12}/><span><ShieldCheck size={15}/>Review</span></div></div><div className="r-dashboard-motto">Disciplined<br/>investing for<br/>a brighter tomorrow.</div></div></>:<div className="r-dashboard-detail"><span className="r-icon-circle">{active==="Research"?<Search/>:active==="Model Portfolios"?<Layers3/>:active==="Reports"?<FileText/>:<Workflow/>}</span><h4>{active==="Research"?"Understand the strategy behind the portfolio.":active==="Model Portfolios"?"A clear portfolio framework.":active==="Rebalance & Orders"?"A structured review and implementation process.":active==="Clients"?"Your relationships. A connected workflow.":active==="Reports"?"Clear context for better conversations.":"A workspace shaped around your firm."}</h4><p>This concept preview illustrates the platform workflow. Strategy figures and client records are not displayed.</p><Link href={active==="Research"?"/research":active==="Model Portfolios"?"/strategies":"/walkthrough"}>Explore further<ArrowRight size={12}/></Link></div>}</div></div></div>;
}

const benefits:{icon:LucideIcon;title:string;copy:string;href:string}[]=[
 {icon:BarChart3,title:"Research-led strategies",copy:"Evidence-based thinking and systematic investment approaches.",href:"/strategies"},
 {icon:Settings,title:"Operational workflows",copy:"A connected approach to research, reporting and deployment.",href:"/platform"},
 {icon:ShieldCheck,title:"Institutional discipline",copy:"A consistent, transparent and documented process.",href:"/institutions"},
 {icon:FileText,title:"Client-ready reporting",copy:"Clear research context for deeper client conversations.",href:"/platform"},
];
const workflow:{icon:LucideIcon;title:string;copy:string}[]=[
 {icon:Search,title:"Research",copy:"Explore strategies and insights"},
 {icon:BarChart3,title:"Model Portfolios",copy:"Understand portfolio construction"},
 {icon:ListChecks,title:"Rebalance & Orders",copy:"Plan the review and implementation process"},
 {icon:FileText,title:"Reporting",copy:"Bring context to client conversations"},
 {icon:PieChart,title:"Monitoring",copy:"Follow portfolio reviews and updates"},
];
const audiences:{icon:LucideIcon;title:string;copy:string;detail:string}[]=[
 {icon:Users,title:"Advisors & RIAs",copy:"Strengthen your investment process and serve clients with clarity.",detail:"Bring systematic research and model portfolio principles into your practice. Explore methodologies, follow publications and keep your advisory team aligned."},
 {icon:Building2,title:"Wealth Managers / MFDs",copy:"Explore research and tools for your professional workflow.",detail:"Discuss the fund-research experience and supporting workflow appropriate to your firm. Research access and capabilities are considered in the context of your role."},
 {icon:Landmark,title:"PMS, AIFs & Family Offices",copy:"Discuss research infrastructure for professional investment teams.",detail:"Explore how documented research and a consistent portfolio framework could fit within your existing investment process. Start with a conversation about your mandate."},
];

function SectionTitle({title,copy}:{title:string;copy?:string}){return <div className="r-section-title"><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>;}
export function WorkflowCards(){return <div className="r-workflow">{workflow.map(({icon:Icon,title,copy},i)=><div className="r-workflow-item" key={title}><Link href="/platform" className="r-workflow-card"><Icon size={29}/><h3>{title}</h3><p>{copy}</p></Link>{i<workflow.length-1&&<ArrowRight className="r-workflow-arrow" size={21}/>}</div>)}</div>;}
export function InstitutionCards(){return <div className="r-institution-cards">{audiences.map(({icon:Icon,title,copy})=><Link href="/institutions" key={title}><Icon size={31}/><div><h3>{title}</h3><p>{copy}</p></div></Link>)}</div>;}
export function ReferenceCTA(){return <section className="r-cta"><div><h2>A better investment process needs<br/>more than ideas. It needs infrastructure.</h2><p>Partner with The Quant Club to bring together research, strategies and operational support—with a disciplined process at the core.</p><div><Link href="/strategies" className="r-button r-button-white">Explore Strategies<ArrowRight size={16}/></Link><Link href="/walkthrough" className="r-button r-button-transparent">Talk to Us</Link></div></div></section>;}

export function ReferenceHome(){const strategyIcons=[BarChart3,TrendingUp,ShieldCheck,Layers3,Droplets,PieChart];return <div className="r-home">
 <section className="r-hero"><Waves id="hero-reference"/><div className="r-container r-hero-inner"><div className="r-hero-copy"><p className="r-eyebrow">DISCIPLINED RESEARCH. PRACTICAL IMPLEMENTATION.</p><h1>Research, strategies, and infrastructure for better <em>investment decisions.</em></h1><p>The Quant Club helps advisors, wealth managers, and institutions build a clearer investment process through research, discipline, and operational support.</p><div className="r-hero-buttons"><Link href="/strategies" className="r-button">Explore Strategies<ArrowRight size={18}/></Link><Link href="/platform" className="r-button r-button-outline">See the Platform</Link></div><span className="r-hero-caption">RESEARCH <i/> STRATEGIES <i/> WORKFLOWS <i/> CLIENT SUPPORT</span></div><div className="r-hero-preview"><DashboardPreview/><span className="r-handwritten">Technology for a more<br/>disciplined tomorrow.<i/></span></div></div></section>
 <section className="r-benefits"><div className="r-container"><SectionTitle title="More than investment strategies." copy="A platform designed to research, implement, and support a better investment process."/><div className="r-benefit-grid">{benefits.map(({icon:Icon,title,copy,href})=><Link href={href} key={title}><span className="r-icon-circle"><Icon size={29}/></span><h3>{title}</h3><p>{copy}</p></Link>)}</div></div></section>
 <section className="r-flow-section"><div className="r-container"><SectionTitle title="A platform that supports the full investment workflow." copy="From research to deployment and monitoring—explore the connected platform vision."/><WorkflowCards/></div></section>
 <section className="r-strategies"><div className="r-container"><div className="r-strategy-heading"><h2>Different strategies. Different opportunities. One disciplined approach.</h2><Link href="/strategies">Explore All Strategies<ArrowRight size={15}/></Link></div><div className="r-strategy-grid">{publicStrategies.map((s,i)=>{const Icon=strategyIcons[i];return <Link key={s.slug} href={`/strategies/${s.slug}`} className={`r-strategy r-tone-${i}`}><div className="r-strategy-banner"><Icon size={26}/><svg viewBox="0 0 160 60" preserveAspectRatio="none" aria-hidden="true"><path d="M0 55L42 26 70 40 120 8 160 40V60H0Z"/></svg></div><div className="r-strategy-text"><span>QUANT ×</span><h3>{s.name}</h3><p>{s.universe}. A systematic research framework.</p></div></Link>;})}</div></div></section>
 <section className="r-institutions"><Waves id="institution-reference"/><div className="r-container"><SectionTitle title="Built for institutions and professional investors." copy="For advisors, RIAs, wealth managers, PMS/AIFs and family offices. Designed around real investment workflows."/><InstitutionCards/><div className="r-institution-values">{[[Droplets,"Deployment awareness"],[Users,"Professional investment use cases"],[Settings,"Operational controls"],[Layers3,"Structured implementation"]].map(([I,title])=>{const Icon=I as LucideIcon;return <span key={String(title)}><Icon size={23}/>{String(title)}</span>;})}</div></div></section>
 <section className="r-process"><div className="r-container"><SectionTitle title="A clear process for more disciplined investing." copy="From idea to implementation—a structured, end-to-end approach."/><div className="r-process-steps">{[{title:"Research",copy:"Explore ideas and investment themes"},{title:"Strategy Design",copy:"Translate research into portfolio frameworks"},{title:"Deployment",copy:"Plan implementation around your firm"},{title:"Monitoring",copy:"Follow reviews and support client conversations"}].map((p,i)=><div key={p.title}><span>{i+1}</span><div><h3>{p.title}</h3><p>{p.copy}</p></div>{i<3&&<ArrowRight size={23}/>}</div>)}</div></div></section><ReferenceCTA/>
 </div>;}

export function InstitutionsPage(){return <><section className="r-institutions-hero"><Waves id="institution-page"/><div className="r-container"><p className="r-eyebrow">FOR INSTITUTIONS & PROFESSIONAL INVESTORS</p><h1>Built around your mandate.<br/><em>Designed for your practice.</em></h1><p>Research, strategy frameworks and a connected platform vision for professional investment teams.</p><Link href="/walkthrough" className="r-button">Talk to our team<ArrowRight size={16}/></Link></div></section><section className="r-institution-details r-container">{audiences.map(({icon:Icon,title,detail})=><article key={title}><span className="r-icon-circle"><Icon size={30}/></span><h2>{title}</h2><p>{detail}</p><Link href="/walkthrough">Discuss your practice<ArrowRight size={15}/></Link></article>)}</section><section className="r-benefits"><div className="r-container"><SectionTitle title="A common framework. A conversation specific to you." copy="Explore the research, the workflow and the boundaries appropriate to your organisation."/><WorkflowCards/><p className="r-role-note"><ShieldCheck size={17}/>The professional firm retains responsibility for client suitability, advice and execution. Available research and tools depend on the firm’s role and approved access.</p></div></section><ReferenceCTA/></>;}

export function ReferencePlatform(){return <><section className="r-platform-hero r-container"><p className="r-eyebrow">RESEARCH. IMPLEMENTATION. SUPPORT.</p><h1>The investment workflow.<br/><em>Brought together.</em></h1><p>Explore the platform vision—from research and model portfolios to reporting and monitoring.</p><DashboardPreview expanded/></section><PlatformCycle/><section className="r-benefits"><div className="r-container"><SectionTitle title="One connected experience for your team." copy="An interactive concept preview of the broader workflow. Product integrations are developed separately."/><WorkflowCards/></div></section><section className="r-platform-capabilities r-container">{benefits.map(({icon:Icon,title,copy})=><article key={title}><span className="r-icon-circle"><Icon size={27}/></span><h2>{title}</h2><p>{copy}</p><span><Check size={13}/>Designed around a documented process</span></article>)}</section><section className="r-platform-boundary r-container"><CircleHelp size={23}/><div><h2>Clear roles. Clear responsibilities.</h2><p>This public preview shows the workflow concept, without strategy figures or client records. Research and member access, operational integrations and client tools are connected through separate product development. Your firm retains its advisory judgement.</p></div></section><ReferenceCTA/></>;}
